import type { Metadata } from "next";
import {Plus_Jakarta_Sans} from 'next/font/google'
import localFont from "next/font/local";
import next from "next";
// import "./globals.css";


const Plus_Jakarta_Sans_init = Plus_Jakarta_Sans ({
subsets:['latin'],
weight:['200','300','400','500','600','700','800'],
variable: '--font-plusJakartaSans',
})


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "3D Viewer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={Plus_Jakarta_Sans_init.variable}>
        {children}
      </body>
    </html>
  );
}
